/* collect.js — the daily collector (Design Doc §3, ADR-001/002/003).
   Run:  node scripts/collect.js          (needs Node 18+, no npm packages)
   Does: fetch → compute Z-MVRV → sanity check → write data/zmvrv.csv + data/zmvrv.js
   Idempotent: running twice on the same day yields the same rows.
   The page only reads data/zmvrv.js; it never knows which source produced the numbers. */

const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '..', 'data');
const CSV = path.join(DATA_DIR, 'zmvrv.csv');
const JS = path.join(DATA_DIR, 'zmvrv.js');
const REFETCH_DAYS = 7;         // free-tier newest days can be preliminary → re-pull a week
const JUMP = 0.5;               // |today − yesterday| above this → suspicious
const RANGE = [-1.5, 12];       // outside this → suspicious
const OUTPUT_FROM = '2011-07-18'; // stdev needs ~1 year of history to mean anything; earlier Z values are artifacts

/* ---------- IndicatorSource implementations (the seam) ---------- */

async function fetchJSON(url) {
  const r = await fetch(url, { headers: { 'user-agent': 'btc-cycle-dashboard/1.0' } });
  if (!r.ok) throw new Error(`HTTP ${r.status} for ${url}`);
  const j = await r.json();
  if (j.error) throw new Error(JSON.stringify(j.error));
  return j;
}

/* Primary: CoinMetrics Community — compute Z ourselves over the FULL history (ADR-001, D5). */
async function coinmetricsFull() {
  let url = 'https://community-api.coinmetrics.io/v4/timeseries/asset-metrics'
    + '?assets=btc&metrics=CapMrktCurUSD,CapMVRVCur&frequency=1d&start_time=2010-07-18&page_size=10000';
  let data = [];
  while (url) { const j = await fetchJSON(url); data = data.concat(j.data); url = j.next_page_url; }
  const rows = data.filter(r => r.CapMrktCurUSD && r.CapMVRVCur)
    .map(r => ({ date: r.time.slice(0, 10), m: +r.CapMrktCurUSD, mvrv: +r.CapMVRVCur }));
  let sum = 0, sum2 = 0, n = 0;
  return rows.map(r => {
    n++; sum += r.m; sum2 += r.m * r.m;
    const mean = sum / n, sd = Math.sqrt(Math.max(sum2 / n - mean * mean, 0));
    const realized = r.m / r.mvrv;
    return { date: r.date, value: sd ? +((r.m - realized) / sd).toFixed(2) : 0, source: 'coinmetrics' };
  }).filter(r => r.date >= OUTPUT_FROM);
}

/* Fallback: bitcoin-data.com ready-made Z (only used when primary fails). */
async function bitcoindataRecent() {
  const j = await fetchJSON('https://bitcoin-data.com/v1/mvrv-zscore?limit=30');
  return j.map(x => ({ date: x.d, value: +(+x.mvrvZscore).toFixed(2), source: 'bitcoindata' }));
}

/* ---------- CSV helpers ---------- */

function readCSV() {
  if (!fs.existsSync(CSV)) return new Map();
  const lines = fs.readFileSync(CSV, 'utf8').trim().split('\n').slice(1);
  const map = new Map();
  for (const l of lines) {
    const [date, value, status, source, note = ''] = l.split(',');
    map.set(date, { date, value: value === '' ? null : +value, status, source, note });
  }
  return map;
}

function writeAll(map) {
  const rows = [...map.values()].sort((a, b) => a.date.localeCompare(b.date));
  const csv = 'date,value,status,source,note\n'
    + rows.map(r => [r.date, r.value ?? '', r.status, r.source, (r.note || '').replace(/,/g, ';')].join(',')).join('\n') + '\n';
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(CSV, csv);
  // JS twin so the page works from file:// and from GitHub Pages without CORS/fetch issues.
  fs.writeFileSync(JS, '/* generated by scripts/collect.js — do not edit */\nwindow.ZMVRV_ROWS = '
    + JSON.stringify(rows.map(r => ({ date: r.date, value: r.value, status: r.status, source: r.source }))) + ';\n');
  return rows;
}

/* ---------- sanity check (PRD §6, Design Doc §4) ---------- */

function applyStatus(rows) {
  // The jump rule guards NEW data only (last REFETCH_DAYS). History is the reference itself —
  // 2013-04 and 2021-05 really did move 4 points in a day.
  const recentCut = new Date(Date.now() - REFETCH_DAYS * 86400000).toISOString().slice(0, 10);
  let prev = null;
  for (const r of rows) {
    if (r.value == null) { r.status = 'missing'; continue; }
    const out = r.value < RANGE[0] || r.value > RANGE[1];
    const jump = prev != null && r.date >= recentCut && Math.abs(r.value - prev) > JUMP;
    if (out || jump) { r.status = 'suspicious'; r.note = out ? `out of range ${RANGE}` : `jump ${(r.value - prev).toFixed(2)} vs prev`; }
    else { r.status = 'ok'; r.note = r.note && r.note.startsWith('jump') ? '' : r.note; }
    prev = r.value;
  }
}

/* ---------- main ---------- */

(async () => {
  const existing = readCSV();
  const todayUTC = new Date().toISOString().slice(0, 10);
  const backfill = existing.size === 0;
  let fresh = [], used = 'coinmetrics', err = '';

  try {
    fresh = await coinmetricsFull();
    if (!backfill) { const cut = new Date(Date.now() - REFETCH_DAYS * 86400000).toISOString().slice(0, 10); fresh = fresh.filter(r => r.date >= cut); }
  } catch (e1) {
    err = 'coinmetrics: ' + e1.message;
    try { fresh = await bitcoindataRecent(); used = 'bitcoindata'; }
    catch (e2) { err += ' | bitcoindata: ' + e2.message; fresh = []; }
  }

  for (const r of fresh) existing.set(r.date, { ...r, status: 'ok', note: '' });

  // Both sources failed → record a visible `missing` row for yesterday (PRD guardrail).
  if (fresh.length === 0) {
    const y = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
    if (!existing.has(y)) existing.set(y, { date: y, value: null, status: 'missing', source: '-', note: err });
  }

  const rows = [...existing.values()].sort((a, b) => a.date.localeCompare(b.date));
  applyStatus(rows);
  writeAll(new Map(rows.map(r => [r.date, r])));

  const last = rows.at(-1);
  console.log(`[collect] ${todayUTC} · rows=${rows.length} · source=${used} · latest=${last.date} value=${last.value} status=${last.status}${err ? ' · ' + err : ''}`);
  if (fresh.length === 0) process.exitCode = 1; // red run in Actions so it's visible
})();
